### ISSUE TITLE
New rule: Extension method variable should be named @this

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#14]
For consistency and clarity, enforce that the first variable in extension methods is named **"@this"**

**Comment by Foroughi** [comment]
@reporter , fixed on `NuGetPackages/05795af9b58a893dfe7118c5fab3d2a566b2a45e`

**Comment by Foroughi** [comment]
Here are some details of the new rule : 

## General Details:

 > ID = "218"
> Category = Category.Naming
> Message = "For consistency and clarity, use '@this' instead of '{0}' for the first paramter of extension methods"
> Severity = DiagnosticSeverity.Warning
> Package = GCop.Common

## Technical Details : 

> As the rule is about Extension Methods, obviously it will be kicked under the following circumstances : 
> 1- The method should be declared as `Static`
> 2 - The method should have at least one argument
> 3 - The first argument should be decorated with the keyword `this`
> 4 - The first argument shouldn't be named as `@this`

In case CGop find any diagnostic regard to this rule, it will provide an action named 'Change to @this' in order to let user fix it. the fix action will change  : 

1 - The argument name in the method declaration 
2 - All the references the argument in the current method body
