### ISSUE TITLE
GCop 516 VS GCop 618

### ISSUE THREAD

**Issue by marjanjavid** [Geeksltd/GCop#146]
It seems these rules are the same

**Comment by Foroughi** [comment]
@marjanjavid  After more investigation on these two rules I have to disagree with you on this b/c they are not the same. Here is more details : 

### GCop618 
This rule looks for this code : `Database.Find(rec => rec.Something == Value)`. Then again the rule will check if there is an static method named `FindBySomething `in the current context and in case it **clould find** it , then will suggest use that method instead of `Find `method  

### GCop516
This rule is  also looks for `Database.Find(rec => rec.Something == Value)`, then again the rull will check if there is an static method named `FindBySomething `in current context and in case it **couldnt find** it, then will suggest the dev to mark  `Something` as unique in its` Mshap Entity` and and then use the generated `FindBySomething `method

**Comment by marjanjavid** [comment]
It is answered in another issue https://github.com/Geeksltd/GCop/issues/151
so I close this one
